# Generated by Django 3.0 on 2020-02-22 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SheetTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='Label')),
            ],
        ),
        migrations.CreateModel(
            name='SheetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Label')),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenu fiche')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('mark', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Note')),
                ('plagiarism_rate', models.PositiveIntegerField(verbose_name='Taux de plagiat')),
                ('creation_date', models.DateField(auto_now=True, verbose_name='Date de creation')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SheetType')),
                ('tags', models.ManyToManyField(to='api.SheetTag')),
            ],
        ),
    ]
