# Generated by Django 3.0 on 2019-12-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, verbose_name='creation_date'),
        ),
    ]
