# Generated by Django 3.0.7 on 2020-09-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='nb_click',
            field=models.IntegerField(default=0),
        ),
    ]
