# Generated by Django 3.0 on 2019-12-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheet',
            old_name='sheettype',
            new_name='subject',
        ),
        migrations.AlterField(
            model_name='sheet',
            name='creation_date',
            field=models.DateField(auto_now=True, verbose_name='Date de creation'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='mark',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Note'),
        ),
    ]
