# Generated by Django 3.0.7 on 2020-10-04 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sheet_nb_click'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sheet',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='sheettag',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='sheettype',
            options={'ordering': ['-id']},
        ),
    ]
