# Generated by Django 3.0 on 2019-12-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sheet_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='creation_date',
            field=models.DateField(auto_now=True, verbose_name='Date creation'),
        ),
    ]
