# Generated by Django 3.0 on 2020-02-24 20:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200224_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='mark',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='plagiarism_rate',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taux de plagiat'),
        ),
    ]
