# Generated by Django 3.0.7 on 2021-04-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210401_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheettag',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
