# Generated by Django 3.0.7 on 2020-10-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201004_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='locale',
            field=models.CharField(choices=[('fr-FR', 'Français'), ('en-EN', 'English')], default='en-EN', max_length=50, verbose_name='Locale'),
        ),
    ]
