# Generated by Django 3.0.7 on 2021-01-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sheet_locale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheettag',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sheettype',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
