# Generated by Django 3.0.7 on 2021-01-05 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210105_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='next_sheet',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='api.Sheet'),
        ),
    ]
