# Generated by Django 3.0.7 on 2021-02-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_sheet_next_sheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheettag',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
