version: "3"

services:
    postgredb:
        restart: always
        image: postgres
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./SQLinit:/docker-entrypoint-initdb.d/
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: alex
    sheetapi:
        build: ./sheetAPI
        command: bash -c "python3 ./sheetAPI/manage.py makemigrations && python3 ./sheetAPI/manage.py migrate && python3 ./sheetAPI/manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/codesheetAPI
        links:
            - postgredb
        depends_on:
            - postgredb
        ports:
            - "8000:8000"
        environment:
            DATABASE_SERVICE_HOST: postgredb
            DATABASE_NAME: sheet_db 
            DATABASE_USER: postgres
            DATABASE_PASSWORD: alex
            DEBUG: "True"
    userapi:
        build: ./userAPI
        command: bash -c "python3 ./userAPI/manage.py makemigrations && python3 ./userAPI/manage.py migrate && python3 ./userAPI/manage.py runserver 0.0.0.0:8001"
        volumes:
            - .:/codeuserAPI
        links:
            - postgredb
        depends_on:
            - postgredb
        ports:
            - "8001:8001"
        environment:
            DATABASE_SERVICE_HOST: postgredb
            DATABASE_NAME: user_db 
            DATABASE_USER: postgres
            DATABASE_PASSWORD: alex
            DEBUG: "True"
    frontend:
        build: ./sheeter_user_interface
        command: ["npm", "run", "start"]
        volumes:
            - ./sheeter_user_interface:/app/
            - node-modules:/app/node_modules
        ports:
            - 3000:3000
        
volumes:
    db-data:
    node-modules: