# Generated by Django 3.0.7 on 2020-09-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SheeterUser',
            fields=[
                ('user_id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Id_ user')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('account_type', models.CharField(choices=[('Fb', 'Facebook'), ('Ggl', 'Google')], max_length=200, verbose_name='Type_compte')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('profile_pic', models.TextField(verbose_name='url_profile_pic')),
            ],
        ),
    ]
