# Generated by Django 3.0.7 on 2020-10-03 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sheeteruser',
            options={'ordering': ['-name']},
        ),
    ]
