# Generated by Django 3.0.7 on 2020-10-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201003_2223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SheeterUser',
        ),
    ]
