# Generated by Django 3.0.7 on 2021-04-05 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Titre')),
                ('code', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Code de la categorie')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='api.Category')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.PositiveIntegerField(default=None, verbose_name='PK message')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date creation')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='api.Response')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('author', models.PositiveIntegerField(verbose_name="PK de l'auteur")),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date creation')),
                ('state', models.CharField(choices=[('T', 'Traité'), ('ECT', 'En cours de traitement'), ('NT', 'Non traité')], default='Non traité', max_length=30, verbose_name='Etat')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Category')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
