# Generated by Django 3.0.7 on 2020-11-20 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titre')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='api.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('author', models.PositiveIntegerField(verbose_name="PK de l'auteur")),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('T', 'Traité'), ('ECT', 'En cours de traitement'), ('NT', 'Non traité')], default='Non traité', max_length=30, verbose_name='Etat')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Category')),
            ],
        ),
    ]
