# Generated by Django 3.0.7 on 2020-11-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201124_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Code de la categorie'),
        ),
    ]
