# Generated by Django 3.0.7 on 2020-11-29 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201129_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Category'),
        ),
    ]
