# Generated by Django 3.0.7 on 2020-12-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201203_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Code de la categorie'),
        ),
    ]
